# Generated by Django 6.1 on 2026-08-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
