# Generated by Django 6.1 on 2026-08-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_item_theme_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.item')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.referentiel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'ref'), name='unique_item_referentiel')],
            },
        ),
    ]
