# Generated by Django 6.1 on 2026-08-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_item_referentiel_itemreferentiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreferentiel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_referentiels', to='studies.item'),
        ),
        migrations.AlterField(
            model_name='itemreferentiel',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_referentiels', to='studies.referentiel'),
        ),
    ]
