# Generated by Django 6.1 on 2026-08-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_itemreferentiel_item_alter_itemreferentiel_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
